workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
      node: 18
      vars:
        REACT_APP_BACKEND_URL: "https://mindspace-preview.preview.emergentagent.com"
        CI: "false"
    scripts:
      - name: Install dependencies
        working_directory: frontend
        script: |
          npm install --legacy-peer-deps
      - name: Build React app
        working_directory: frontend
        script: |
          npm run build
      - name: Sync Capacitor
        working_directory: frontend
        script: |
          npx cap sync android
      - name: Build Android APK
        working_directory: frontend/android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
