workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 21
      node: 20
    scripts:
      - name: Install dependencies
        working_directory: frontend
        script: |
          npm install --legacy-peer-deps
          npm install ajv@^8 --save --legacy-peer-deps
      - name: Setup environment
        working_directory: frontend
        script: |
          echo "REACT_APP_BACKEND_URL=https://mindspace-preview.preview.emergentagent.com" > .env
          echo "CI=false" >> .env
      - name: Build React app
        working_directory: frontend
        script: |
          CI=false npm run build
      - name: Sync Capacitor
        working_directory: frontend
        script: |
          npx cap sync android
      - name: Generate Keystore
        working_directory: frontend/android
        script: |
          keytool -genkeypair -v \
            -keystore mindspace.keystore \
            -alias mindspace \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass mindspace123 \
            -keypass mindspace123 \
            -dname "CN=MindSpace, OU=App, O=MindSpace, L=US, ST=US, C=US"
      - name: Build Signed Release Bundle
        working_directory: frontend/android
        script: |
          ./gradlew bundleRelease
    artifacts:
      - frontend/android/app/build/outputs/**/*.aab
      - frontend/android/mindspace.keystore
