workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      java: 17
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build React app
        script: |
          cd frontend
          npm run build
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync android
      - name: Build Android APK
        script: |
          cd frontend/android
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
