workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 21
      node: 20
    scripts:
      - name: Install dependencies
        working_directory: frontend
        script: |
          npm install --legacy-peer-deps
          npm install ajv@^8 --save --legacy-peer-deps
      - name: Setup environment
        working_directory: frontend
        script: |
          echo "REACT_APP_BACKEND_URL=https://mindspace-preview.preview.emergentagent.com" > .env
          echo "CI=false" >> .env
      - name: Build React app
        working_directory: frontend
        script: |
          CI=false npm run build
      - name: Sync Capacitor
        working_directory: frontend
        script: |
          npx cap sync android
      - name: Create Upload Keystore
        working_directory: frontend/android
        script: |
          # Create the upload keystore for Google Play
          keytool -genkeypair \
            -v \
            -storetype JKS \
            -keystore mindspace-upload-key.jks \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass MindSpace2024! \
            -keypass MindSpace2024! \
            -dname "CN=MindSpace App, OU=Mobile Development, O=Sarenity Rhain, L=United States, ST=US, C=US"
          
          echo "Keystore created successfully!"
          echo ""
          echo "========================================="
          echo "SAVE THESE CREDENTIALS!"
          echo "========================================="
          echo "Keystore file: mindspace-upload-key.jks"
          echo "Alias: upload"
          echo "Store Password: MindSpace2024!"
          echo "Key Password: MindSpace2024!"
          echo "========================================="
      - name: Build Signed Release Bundle
        working_directory: frontend/android
        script: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/mindspace-upload-key.jks \
            -Pandroid.injected.signing.store.password=MindSpace2024! \
            -Pandroid.injected.signing.key.alias=upload \
            -Pandroid.injected.signing.key.password=MindSpace2024!
          
          echo ""
          echo "Build complete! Download both files:"
          echo "1. app-release.aab (upload to Play Store)"
          echo "2. mindspace-upload-key.jks (SAVE FOREVER)"
    artifacts:
      - frontend/android/app/build/outputs/bundle/release/app-release.aab
      - frontend/android/mindspace-upload-key.jks
